# Generated by kw-nix/scripts/gen-flakes.sh from kw-nix/lib/graph.nix.
# Edit graph.nix and regenerate; only depsHash is maintained in place.
{
  description = "kwatcher umbrella: example app + kwev";

  inputs = {
    kw-nix.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-nix.git";
    kw-core.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-core.git";
    kw-core.inputs.kw-nix.follows = "kw-nix";
    kw-runtime.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-runtime.git";
    kw-runtime.inputs.kw-nix.follows = "kw-nix";
    kw-amqp.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-amqp.git";
    kw-amqp.inputs.kw-nix.follows = "kw-nix";
    kw-protocol.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-protocol.git";
    kw-protocol.inputs.kw-nix.follows = "kw-nix";
    kw-http.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-http.git";
    kw-http.inputs.kw-nix.follows = "kw-nix";
    kw-cron.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-cron.git";
    kw-cron.inputs.kw-nix.follows = "kw-nix";
    kw-action.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-action.git";
    kw-action.inputs.kw-nix.follows = "kw-nix";
    kw-signal.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-signal.git";
    kw-signal.inputs.kw-nix.follows = "kw-nix";
    kw-kwev.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-kwev.git";
    kw-kwev.inputs.kw-nix.follows = "kw-nix";
    kw-docgen.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen.git";
    kw-docgen.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-http.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-http.git";
    kw-docgen-http.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-amqp.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-amqp.git";
    kw-docgen-amqp.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-cron.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-cron.git";
    kw-docgen-cron.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-signal.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-signal.git";
    kw-docgen-signal.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-http-client.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-http-client.git";
    kw-docgen-http-client.inputs.kw-nix.follows = "kw-nix";
    kw-docgen-sqlite.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-docgen-sqlite.git";
    kw-docgen-sqlite.inputs.kw-nix.follows = "kw-nix";
    kw-asyncapi.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-asyncapi.git";
    kw-asyncapi.inputs.kw-nix.follows = "kw-nix";
    kw-http-template.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-http-template.git";
    kw-http-template.inputs.kw-nix.follows = "kw-nix";
    kw-sqlite.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-sqlite.git";
    kw-sqlite.inputs.kw-nix.follows = "kw-nix";
    kw-http-client.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-http-client.git";
    kw-http-client.inputs.kw-nix.follows = "kw-nix";
    kw-auth-oidc.url = "git+ssh://git@git.kalelzar.xyz/kalelzar/kw-auth-oidc.git";
    kw-auth-oidc.inputs.kw-nix.follows = "kw-nix";
  };

  outputs = inputs: inputs.kw-nix.lib.mkKwUmbrella {
    inherit (inputs) self;
    deps = [ inputs.kw-core inputs.kw-runtime inputs.kw-amqp inputs.kw-protocol inputs.kw-http inputs.kw-cron inputs.kw-action inputs.kw-signal inputs.kw-kwev inputs.kw-docgen inputs.kw-docgen-http inputs.kw-docgen-amqp inputs.kw-docgen-cron inputs.kw-docgen-signal inputs.kw-docgen-http-client inputs.kw-docgen-sqlite inputs.kw-asyncapi inputs.kw-http-template inputs.kw-sqlite inputs.kw-http-client inputs.kw-auth-oidc ];
    depsHash = "sha256-adGt9cDvhgw6nhebiHlsl04w0oqzJq0230L1NtgXci8=";
  };
}
